#!/bin/bash

set -e

MAXNODE=${BBSNODES:-1}

if [ "$1" -gt "$MAXNODE" ]; then
  exec sleep 900d  # OK, so it's not forever, but close enough.
  exit 0           # Just to be really clear!
fi

NODE="$1"
NODEPORT=$(($NODE + 7000))

echo "Starting up node $NODE on port $NODEPORT"
CONFIGFILE="/tmp/dosbox-node$NODE.conf"

sed -e "s/__LISTEN_PORT__/$NODEPORT/" \
    -e "s/__NODE__/$NODE/" \
  < /dos/dosbox-telnetbbs-template.conf > "$CONFIGFILE"

exec dosbox -conf "$CONFIGFILE"

