#!/bin/bash

set -e

MAXNODE=${BBSNODES:-1}

CMDLINE=""

for NODE in `seq 1 $MAXNODE`; do
  NODEPORT=$(($NODE + 7000))
  CMDLINE="$CMDLINE 127.0.0.1:$NODEPORT:1"
done

set -x
exec balance -d -f 23 $CMDLINE

