#!/bin/bash

echo " *** startvnc script"
set -e

if [ -z "$VNCPASSWORD" ]; then
  VNCPASSWORD=`pwgen 8`
  echo " *** VNC password for this session: $VNCPASSWORD"
fi

export USER="`whoami`"
mkdir -p ~/.vnc

echo "$VNCPASSWORD" | tightvncpasswd -f > ~/.vnc/passwd
chmod 0600 ~/.vnc/passwd

tightvncserver -geometry 1024x768 :1
sleep 1
tail -f ~/.vnc/*.log

